db:
    image: mysql
    container_name: ec-mysql
    volumes:
        - ../mysql:/var/lib/mysql
    env_file:
        - common.env
        - database.env
    privileged: true

data:
    image: dylanlindgren/docker-laravel-data
    container_name: ec-data
    volumes:
        - ../lumen:/data
    env_file:
        - common.env
    privileged: true

php:
    image: ppoffice/docker-laravel-phpfpm
    container_name: ec-php
    volumes_from:
        - data
    links:
        - db:db
    env_file:
        - common.env
    privileged: true

web:
    image: dylanlindgren/docker-laravel-nginx
    container_name: ec-web
    volumes_from:
        - data
    links:
        - php:fpm
    ports:
        - 8080:80
    env_file:
        - common.env
    privileged: true

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ec-phpmyadmin
    links:
        - db:db
    restart: always
    environment:
        - PMA_HOST=db
    env_file:
        - common.env
    ports:
        - 8081:80

node:
    build: ./node
    container_name: ec-node
    volumes:
        - ../node:/data
    links:
        - db:db
    ports:
        - 10000:10000
    env_file:
        - common.env

composer:
    image: ppoffice/docker-laravel-composer
    container_name: ec-composer
    volumes_from:
        - data
    env_file:
        - common.env

artisan:
    image: ppoffice/docker-laravel-artisan
    container_name: ec-artisan
    volumes_from:
        - data
    links:
        - db:db
    env_file:
        - common.env
