db:
    image: mysql
    container_name: ec-mysql
    # entrypoint: /localdb-run.sh               # For OS X only
    volumes:
        # - ./localdb-run.sh:/localdb-run.sh    # For OS X only
        # - ../mysql:/mysql                     # For OS X only
        - ../mysql:/var/lib/mysql
    env_file: .env
    privileged: true

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ec-phpmyadmin
    links:
        - db:db
    restart: always
    environment:
        - PMA_HOST=db
    env_file: .env
    ports:
        - 8081:80

data:
    image: dylanlindgren/docker-laravel-data
    container_name: ec-data
    volumes:
        - ../lumen:/data
    privileged: true

php:
    image: ppoffice/docker-laravel-phpfpm
    container_name: ec-php
    volumes_from:
        - data
    links:
        - db:db
    privileged: true

web:
    image: dylanlindgren/docker-laravel-nginx
    container_name: ec-web
    volumes_from:
        - data
    links:
        - php:fpm
    ports:
        - 8080:80
    privileged: true

composer:
    image: dylanlindgren/docker-laravel-composer
    container_name: ec-composer
    volumes_from:
        - data

artisan:
    image: dylanlindgren/docker-laravel-artisan
    container_name: ec-artisan
    volumes_from:
        - data
    links:
        - db:db

socket:
    image: dylanlindgren/docker-laravel-artisan
    container_name: ec-socket
    volumes_from:
        - data
    links:
        - db:db
    ports:
        - 10000:10000
    command: socket:start