db:
    image: mysql
    container_name: gedc-mysql
    entrypoint: /localdb-run.sh               # For OS X only
    volumes:
        - ./localdb-run.sh:/localdb-run.sh    # For OS X only
        - ../mysql:/mysql                     # For OS X only
    env_file:
        - common.env
        - database.env
    privileged: true

data:
    image: dylanlindgren/docker-laravel-data
    container_name: gedc-data
    volumes:
        - ../lumen:/data
    env_file:
        - common.env
    privileged: true

php:
    image: ppoffice/docker-laravel-phpfpm
    container_name: gedc-php
    volumes_from:
        - data
    links:
        - db:db
    env_file:
        - common.env
    privileged: true

web:
    image: dylanlindgren/docker-laravel-nginx
    container_name: gedc-web
    volumes_from:
        - data
    links:
        - php:fpm
    ports:
        - 8080:80
    env_file:
        - common.env
    privileged: true

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gedc-phpmyadmin
    links:
        - db:db
    restart: always
    environment:
        - PMA_HOST=db
    env_file:
        - common.env
    ports:
        - 8081:80

cache:
    image: redis
    container_name: gedc-cache
    privileged: true
    # ports:
    #     - 6379:6379

node:
    build: ./node
    container_name: gedc-node
    volumes:
        - ../node:/data
    links:
        - db:db
        - cache:cache
    ports:
        - 10000:10000
    env_file:
        - common.env

python:
    build: ./python
    container_name: gedc-python
    volumes:
        - ../python:/data
    links:
        - cache:cache
    env_file:
        - common.env

composer:
    image: ppoffice/docker-laravel-composer
    container_name: gedc-composer
    volumes_from:
        - data
    env_file:
        - common.env

artisan:
    image: ppoffice/docker-laravel-artisan
    container_name: gedc-artisan
    volumes_from:
        - data
    links:
        - db:db
    env_file:
        - common.env
